if(NOT latCore)
    set(DIR_LATINO_H ${CMAKE_SOURCE_DIR}/latino-core/include/latino.h)
else()
    set(DIR_LATINO_H ${CMAKE_SOURCE_DIR}/include/latino.h)
endif()

string(TIMESTAMP TODAY "%Y")
set(CURRENT_YEAR ${TODAY})

file(READ ${DIR_LATINO_H} _LATINO_H_CONTENTS)

string(REGEX MATCH  "#define LAT_VERSION_MAYOR   ([0-9]*)"  LAT_VER_MAYOR "${_LATINO_H_CONTENTS}")
string(REPLACE      "#define LAT_VERSION_MAYOR   " ""       LAT_VER_MAYOR "${LAT_VER_MAYOR}")

string(REGEX MATCH  "#define LAT_VERSION_MENOR   ([0-9]*)"  LAT_VER_MENOR "${_LATINO_H_CONTENTS}")
string(REPLACE      "#define LAT_VERSION_MENOR   " ""       LAT_VER_MENOR "${LAT_VER_MENOR}")

string(REGEX MATCH  "#define LAT_VERSION_PARCHE  ([0-9]*)"  LAT_VER_PARCHE "${_LATINO_H_CONTENTS}")
string(REPLACE      "#define LAT_VERSION_PARCHE  " ""       LAT_VER_PARCHE "${LAT_VER_PARCHE}")

if(BUILD_NUMBER)
    set(LATINO_VERSION ${LAT_VER_MAYOR}.${LAT_VER_MENOR}.${LAT_VER_PARCHE}.${BUILD_NUMBER})
else()
    set(LATINO_VERSION ${LAT_VER_MAYOR}.${LAT_VER_MENOR}.${LAT_VER_PARCHE}.0)
endif()

string(REGEX REPLACE        "#define LAT_CURRENT_YEAR    ([0-9]*)" "#define LAT_CURRENT_YEAR    ${CURRENT_YEAR}"    _LATINO_H_CONTENTS "${_LATINO_H_CONTENTS}")
file(WRITE ${DIR_LATINO_H}  "${_LATINO_H_CONTENTS}")